### ISSUE TITLE
Contributing guide can be improved for those unfamiliar with DocBook ecosystem

### ISSUE THREAD

**Issue by kalabiyau** [SUSE/doc-sle#39]
https://github.com/SUSE/doc-sle#contributing holds only a reference to a way how development is done, but not even a link to docs where one can figure out how to preview his changes before making Pull Request

**Comment by sknorr** [comment]
I have added https://github.com/SUSE/doc-sle#writing-docbook . Hope that helps. Leaving this bug open in case I forgot something important.

**Comment by kalabiyau** [comment]
@sknorr great! Thanks a lot!
